public enum EJPTJGENOIN
{
	UNSET = 0,
	KILL_ENEMIES = 1,
	COMPLETE_STAGES = 2,
	SHOOT_BULLETS = 3,
	SURVIVE_WAVES = 4,
	COMPLETE_IN_SECONDS = 5,
	DONT_GET_HIT = 7,
	PICKUP_DROPS = 8,
	DEAL_CRIT = 9,
	COMPLETE_LEVEL = 10,
	SPEND_RAID_TICKETS = 11,
	BUY_ITEM_FROM_DAILY_SHOP = 12,
	GAIN_ELITE_PASS_XP = 13,
	CRAFT_GEAR_IN_WORKSHOP = 14,
	CRAFT_TOOLS_IN_WORKSHOP = 15,
	SALVAGE_WEAPONS = 16,
	CRAFT_IN_WORKSHOP = 17,
	COMPLETE_THREAT_5 = 18,
	PLAY_LEVEL = 19
}
