public enum ITTKIKLHHEQ
{
	DAMAGE_PERCENT = 1,
	HEALTH_PERCENT = 2,
	CRIT_CHANCE = 3,
	RELOAD_COOLDOWN = 4,
	EXPLOSION_AREA = 5,
	PIERCE_CHANCE = 6,
	RICOCHET_CHANCE = 7,
	CRIT_DAMAGE = 8,
	EXTRA_LIFE = 9,
	PROJECTILE_DODGE_CHANCE = 10,
	FREEZE_ON_KILL = 11,
	STUN_ON_KILL = 12,
	ZAP_ELECTRICITY_ON_KILL = 13,
	BLOOD_BLAST_ON_KILL = 14,
	TOXIC_BULLETS = 15,
	EXPLODING_BULLETS = 16
}
