public enum RFIHHGOILFG
{
	CHEST_CASH_INCREASE = 0,
	REVIVE_PRICE_CUT_IN_HALF_CHANCE = 1,
	HUNT_INCREASE_TOOL_CHANCE_FROM_LOOTBOX = 2000,
	HUNT_CHANCE_MULTIPLIER_HIGH_GRADE_WEAPONS = 2001,
	OP_HAMMER_CHANCE_LOOTBOX = 3000,
	OP_GAMBLE_REWARD_BOOST_CHANCE = 3001,
	OP_SHARD_INCREASE = 3002,
	EXPEDITION_GAMBLE_REWARD_BOOST_CHANCE = 4000,
	EXPEDITION_EXTRA_HOUSE_TOKENS_LAST = 4001,
	SKIRMISH_RARE_REWARD_CHANCE_MULTIPLIER = 5000,
	SKIRMISH_GAMBLE_REWARD_BOOST_CHANCE = 5001,
	SKIRMISH_GAMBLE_EXTRA_HAMMER_COUNT = 5002,
	WORKSHOP_CASH_COST_REDUCTION = 6000
}
