using System;

[Obsolete]
public enum SHTSPMQQFMP
{
	UNSET = 0,
	SUNGLASSES = 1,
	GOGGLES = 2,
	HELMET = 3,
	CAP = 4,
	FEDORA_HAT = 5,
	COMTACS = 6,
	NIGHT_VISION = 7,
	ARMOR_VEST = 8,
	RIG = 9,
	SHIRT = 10,
	SUIT = 11,
	JACKET = 12,
	WATCH = 13,
	GLOVES = 14,
	SMART_WATCH = 15,
	BRACELET = 16,
	DRONE = 17,
	SCIFI_DRONE = 18,
	RED_DRONE = 19,
	QUADE_DRONE = 20,
	TRIPLE_DRONE = 21,
	FLAPPY_DRONE = 22,
	RC_CAR_RED = 23,
	HOOVER_DRONE = 24,
	RC_CAR_SALAD = 25,
	RC_CAR_RACER = 26,
	ARMOR_PLATE = 27,
	AGENT_CAP = 28,
	PARADE_JACKET = 29,
	RING_GOLDBLUE = 30,
	TRIPLE_WATCH = 31,
	BERETTE_BROWN = 32
}
