using UnityEngine;

[CreateAssetMenu]
public class SpecialLootConfigData : LootConfigData
{
	public enum IJIFHOIRNIT
	{
		MINI_BOSSES = 777,
		MINI_BOSSES_RIFTS = 778,
		LOOTBOX_AGENT_CARDS = 400,
		LOOTBOX_REGULAR = 401,
		LOOTBOX_SCRAP = 402,
		OPERATIONS_CHEST_EASY = 500,
		OPERATIONS_CHEST_MEDIUM = 501,
		OPERATIONS_CHEST_HARD = 502,
		OPERATIONS_CHEST_EXTREME = 503
	}

	public IJIFHOIRNIT id;
}
